# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-GB"
title: "Julian Pietsch"
subtitle: "Dynamics of metabolism and ageing"
name: "Julian Pietsch"
email: julian.pietsch@synmikro.mpi-marburg.mpg.de
description: >- # this means to ignore newlines until "baseurl:"
  Postdoc at the MPI for Terrestrial Microbiology in Marburg investigating
  dynamic processes in bacteria, yeast and cyanobacteria
baseurl: "" # the subpath of your site, e.g. /blog
domain: julianpietsch.github.io
url: https://julianpietsch.github.io  # the base hostname & protocol for your site, e.g. http://example.com
repository: "julianpietsch/julianpietsch.github.io"
twitter_username: JulianPietsch
github_username:  julianpietsch

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-include-cache
  - jekyll-feed

atom_feed:
  hide: true

author:
  name: "Julian Pietsch"
  avatar: "/assets/images/bio-photo.jpg"
  bio: >-
    Postdoc at the
    [MPI for Terrestrial Microbiology](https://www.mpi-marburg.mpg.de/sourjik)
    investigating dynamic processes in bacteria, yeast and cyanobacteria
  location: "Marburg, Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jmjpietsch"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/julianpietsch"
      

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
